AllCops:
  Include:
    - '*.gemspec'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
  Exclude:
    - 'vendor/**/*'

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: separator

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - '*.gemspec'
    - 'Guardfile'

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false
